
export const Users = [
  {
    id: 1,
    profilePicture: "assets/kim.webp",
    username: "Kim Kardashian",
  },
  {
    id: 2,
    profilePicture: "assets/taylor.jpeg",
    username: "Taylor Swift",
  },
  {
    id: 3,
    profilePicture: "assets/john.jpeg",
    username: "John Legend",
  },
  {
    id: 4,
    profilePicture: "assets/jayz.webp",
    username: "Jay-Z",
  },
  {
    id: 5,
    profilePicture: "assets/justin.jpeg",
    username: "Justin Bieber",
  },
  {
    id: 6,
    profilePicture: "assets/donaldtrump.webp",
    username: "Donald Trump",
  },
  {
    id: 7,
    profilePicture: "assets/jamief.webp",
    username: "Jamie Foxx",
  },
  {
    id: 8,
    profilePicture: "assets/wills.jpeg",
    username: "Will Smith",
  },
  {
    id: 9,
    profilePicture: "assets/lebron.jpeg",
    username: "Lebron James",
  },
  {
    id: 10,
    profilePicture: "assets/kh.jpeg",
    username: "Kevin Hart",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/kimkar2.webp",
    date: "5 mins ago",
    userId: 1,
    like: 30000000,
    comment: 589834084,
  },
  {
    id: 2,
    photo: "assets/taylorgrammy.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 12490039020,
    comment: 5495749,
  },
  {
    id: 3,
    desc: "My family is beautiful!!",
    photo: "assets/johnfam.webp",
    date: "1 hour ago",
    userId: 3,
    like: 614958,
    comment: 3893928,
  },
  {
    id: 4,
    photo: "assets/jayandsharp.webp",
    date: "4 hours ago",
    userId: 4,
    like: 76236723,
    comment: 34843,
  },
  {
    id: 5,
    photo: "assets/jandh.webp",
    date: "9 hours ago",
    userId: 5,
    like: 233434947,
    comment: 5494,
  },
  {
    id: 6,
    photo: "assets/trump.webp",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/assets/jf.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52237,
    comment: 332,
  },
  {
    id: 8,
    photo: "assets/willslap.webp",
    date: "3 days ago",
    userId: 8,
    like: 153723727,
    comment: 120302,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/greatness.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 1137273,
    comment: 223988,
  },
  {
    id: 10,
    photo: "assets/hartkev.webp",
    date: "1 week ago",
    userId: 10,
    like: 10893284,
    comment: 123233,
  },
];